### ISSUE TITLE
panic: interface conversion: interface {} is nil, not *types.Block

### ISSUE THREAD

**Issue by matyushkins** [XinFinOrg/XDPoSChain#146]
Hi.
Node v1.4.3

Error
```
WARN [11-22|09:19:53] Rewinding blockchain                     target=0
panic: interface conversion: interface {} is nil, not *types.Block

goroutine 1 [running]:
github.com/XinFinOrg/XDPoSChain/core.(*BlockChain).CurrentBlock(...)
	/work/xdcchain/core/blockchain.go:461
github.com/XinFinOrg/XDPoSChain/core.(*BlockChain).SetHead(0xc001f42000, 0x0, 0x0, 0x0)
	/work/xdcchain/core/blockchain.go:402 +0xc5b
github.com/XinFinOrg/XDPoSChain/core.(*BlockChain).ResetWithGenesisBlock(0xc001f42000, 0xc000150090, 0x0, 0x0)
	/work/xdcchain/core/blockchain.go:563 +0x64
github.com/XinFinOrg/XDPoSChain/core.(*BlockChain).Reset(0xc001f42000, 0x131d57a, 0x23)
	/work/xdcchain/core/blockchain.go:556 +0x37
github.com/XinFinOrg/XDPoSChain/core.(*BlockChain).loadLastState(0xc001f42000, 0x0, 0xc000150090)
	/work/xdcchain/core/blockchain.go:291 +0x1a28
github.com/XinFinOrg/XDPoSChain/core.NewBlockChain(0x16e50a0, 0xc000a70dc0, 0xc001f1dce0, 0xc000164d00, 0x16df0c0, 0xc0010d23c0, 0x0, 0x0, 0x0, 0x0, ...)
	/work/xdcchain/core/blockchain.go:235 +0x770
github.com/XinFinOrg/XDPoSChain/core.NewBlockChainEx(0x16e50a0, 0xc000a70dc0, 0x7fd1340af058, 0xc000770360, 0xc001f1dce0, 0xc000164d00, 0x16df0c0, 0xc0010d23c0, 0x0, 0x0, ...)
	/work/xdcchain/core/blockchain.go:258 +0xbc
github.com/XinFinOrg/XDPoSChain/eth.New(0xc00077c2c0, 0xc000136000, 0xc00069b480, 0xc00007de80, 0x0, 0xffffffffffffffff, 0x0)
	/work/xdcchain/eth/backend.go:176 +0x809
github.com/XinFinOrg/XDPoSChain/cmd/utils.RegisterEthService.func2(0xc00077c2c0, 0xc000019830, 0xc000624c38, 0xc0008c83f8, 0x0)
	/work/xdcchain/cmd/utils/utils.go:27 +0xce
github.com/XinFinOrg/XDPoSChain/node.(*Node).Start(0xc0001d4c80, 0x0, 0x0)
	/work/xdcchain/node/node.go:183 +0x3f9
github.com/XinFinOrg/XDPoSChain/cmd/utils.StartNode(0xc0001d4c80)
	/work/xdcchain/cmd/utils/cmd.go:66 +0x2f
main.startNode(0xc0001569a0, 0xc0001d4c80, 0x0, 0x32, 0x0, 0x0, 0x0, 0x64, 0x0, 0x400, ...)
	/work/xdcchain/cmd/XDC/main.go:228 +0x89
main.XDC(0xc0001569a0, 0xe, 0x1908b100)
	/work/xdcchain/cmd/XDC/main.go:218 +0xf0
gopkg.in/urfave/cli%2ev1.HandleAction(0x1111980, 0x148d9c0, 0xc0001569a0, 0xc0000a6900, 0x0)
	/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0xc8
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc00010c1a0, 0xc000032200, 0x20, 0x20, 0x0, 0x0)
	/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x5dd
main.main()
	/work/xdcchain/cmd/XDC/main.go:207 +0x55
runtime: note: your Linux kernel may be buggy
runtime: note: see https://golang.org/wiki/LinuxKernelSignalVectorBug
runtime: note: mlock workaround for kernel bug failed with errno 12

```

**Comment by AnilChinchawale** [comment]
This issue has been fixed, Kindly follow the below step to use the snapshot for quick sync.

Download Zip File of Chain Data (approx. 32 min to download)

sudo docker-compose -f docker-services.yml down
wget https://download.xinfin.network/xdcchain.tar
tar -xvzf xdcchain.tar
mv xdcchain/XDC xdcchain/oldXDC
mv XDC xdcchain/XDC
rm -rf xdcchain/XDC/nodekey
docker-compose -f docker-services.yml up -d
