### ISSUE TITLE
Error message during syncing

### ISSUE THREAD

**Issue by APshenkin** [XinFinOrg/XDPoSChain#156]
```
INFO [01-05|18:52:19] Imported new chain segment               blocks=2 txs=84 mgas=0.000 elapsed=1.854s mgasps=0.000 number=39557087 hash=643b76…772f9c cache=0.00B
INFO [01-05|18:52:25] It's time to update new set of masternodes for the next epoch...
You've encountered a sought after, hard to reproduce bug. Please report this to the developers <3 https://github.com/XinFinOrg/XDPoSChain/issues
index allocation went beyond available resultCache space
/XDCchain/eth/downloader/queue.go:510
goroutine 29262 [running]:
runtime/debug.Stack(0x26, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/XinFinOrg/XDPoSChain/common.Report(0xc02b8e7a28, 0x1, 0x1)
	/XDCchain/common/debug.go:35 +0x1a5
github.com/XinFinOrg/XDPoSChain/eth/downloader.(*queue).reserveHeaders(0xc014f2e600, 0xc15ffca870, 0x80, 0xc0547ee2a0, 0xc014f37c98, 0xc0547ee2d0, 0xc0547ee300, 0x1497c30, 0x0, 0x0, ...)
	/XDCchain/eth/downloader/queue.go:510 +0x6cb
github.com/XinFinOrg/XDPoSChain/eth/downloader.(*queue).ReserveBodies(0xc014f2e600, 0xc15ffca870, 0x80, 0x0, 0xc15ffca800, 0x0, 0x0)
	/XDCchain/eth/downloader/queue.go:462 +0xeb
github.com/XinFinOrg/XDPoSChain/eth/downloader.(*Downloader).fetchParts(0xc065b54d80, 0x16b9180, 0xc000013480, 0xc014f0ec00, 0xc02b8e7e90, 0xc010056770, 0xc02b8e7e80, 0xc02b8e7ef0, 0xc02b8e7ee0, 0xc02b8e7ed0, ...)
	/XDCchain/eth/downloader/downloader.go:1116 +0x866
github.com/XinFinOrg/XDPoSChain/eth/downloader.(*Downloader).fetchBodies(0xc065b54d80, 0x25b97de, 0x457356, 0x149a3d8)
	/XDCchain/eth/downloader/downloader.go:937 +0x307
github.com/XinFinOrg/XDPoSChain/eth/downloader.(*Downloader).syncWithPeer.func4(0xe9fa452fac21c3af, 0xc161d47720)
	/XDCchain/eth/downloader/downloader.go:466 +0x36
github.com/XinFinOrg/XDPoSChain/eth/downloader.(*Downloader).spawnSync.func1(0xc034976da0, 0xc11a3fad80, 0xc09cf778c0)
	/XDCchain/eth/downloader/downloader.go:486 +0x53
created by github.com/XinFinOrg/XDPoSChain/eth/downloader.(*Downloader).spawnSync
	/XDCchain/eth/downloader/downloader.go:486 +0xc3
#### BUG! PLEASE REPORT ####
```

**Comment by AnilChinchawale** [comment]
Thank you for reporting, We have fixed this issue in the latest release v1.4.4.
