### ISSUE TITLE
package keystore panic sometimes when make test

### ISSUE THREAD

**Issue by gzliudan** [XinFinOrg/XDPoSChain#440]
When I run `make test`, package keystore sometimes panic:

```text
?       github.com/XinFinOrg/XDPoSChain/internal/ethapi [no test files]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x5d221c]

goroutine 25 [running]:
github.com/XinFinOrg/XDPoSChain/accounts/keystore.skipKeyFile({0x0, 0x0})
        /home/me/XDPoSChain/accounts/keystore/file_cache.go:97 +0x1c
github.com/XinFinOrg/XDPoSChain/accounts/keystore.(*fileCache).scan(0xc0000fc290, {0xc0000d0060, 0x18})
        /home/me/XDPoSChain/accounts/keystore/file_cache.go:64 +0x437
github.com/XinFinOrg/XDPoSChain/accounts/keystore.(*accountCache).scanAccounts(0xc0000fc240)
        /home/me/XDPoSChain/accounts/keystore/account_cache.go:235 +0x38
github.com/XinFinOrg/XDPoSChain/accounts/keystore.(*watcher).loop(0xc0000d51e0)
        /home/me/XDPoSChain/accounts/keystore/watch.go:104 +0x46b
created by github.com/XinFinOrg/XDPoSChain/accounts/keystore.(*watcher).start in goroutine 21
        /home/me/XDPoSChain/accounts/keystore/watch.go:52 +0x66
FAIL    github.com/XinFinOrg/XDPoSChain/internal/guide  5.611s
ok      github.com/XinFinOrg/XDPoSChain/internal/jsre   (cached)
```

Another test fail case:

![image](https://github.com/XinFinOrg/XDPoSChain/assets/7695325/85a473d2-265e-4b60-bf4d-785b304cf3dc)

**Comment by gzliudan** [comment]
Closed by #441.
